In [1]:
import numpy as np


In [5]:
arr=np.array(["1","2.2","5"],dtype="float32")
print(arr.dtype)
for i in arr:
    print(i)

float32
1.0
2.2
5.0


In [10]:
arr=np.array(["1","2","5"],dtype="float")
arr=arr.astype("int16")
arr


array([1, 2, 5], dtype=int16)

In [17]:
arr1=np.array([ [1,2,5], [7,8,9]], dtype="int")
arr1.shape
arr1.size
np.info
arr1.item


<function ndarray.item>

In [21]:
np.random.rand()

0.7124033118359681

In [25]:
np.random.seed(24)
np.random.rand()


0.9600173033359185

In [26]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [27]:
#### 2. Print the numpy version and the configuration (★☆☆)
import numpy as np
print("NumPy version:", np.__version__)
print("\nNumPy configuration:")
print(np.show_config())


NumPy version: 1.24.3

NumPy configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Amr chetos/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Amr chetos/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Amr chetos/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Amr chetos/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Amr chetos/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Amr chetos/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Amr chetos/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', 

In [28]:
#### 3. Create a null vector of size 10 (★☆☆)
vector= np.zeros(10)
print (vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
#### 4. How to find the memory size of any array (★☆☆)
arr1 = np.array([[1, 2, 5], [7, 8, 9]], dtype="i4")
memorysize = arr1.nbytes

print( memorysize, "bytes")

24 bytes


In [40]:
#### 5. How to get the documentation of the numpy add function from the command line? 
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [43]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
vectoros=np.zeros(10)
vectoros[4]=1
vectoros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [46]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [48]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
v=np.arange(1,16)
v[::-1]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [54]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
arr=np.array ([[0,1,2],[3,4,5],[5,6,7]])
print (arr)
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [5 6 7]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)
print ( nonzero_indices)

(array([0, 1, 4], dtype=int64),)


In [64]:
#### 11. Create a 3x3 identity matrix (★☆☆)
mat=np.eye(3)
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
arr=np.random.rand(3,3,3)
arr

array([[[0.69951205, 0.99986729, 0.2200673 ],
        [0.36105635, 0.73984099, 0.99645573],
        [0.31634698, 0.13654458, 0.38398001]],

       [[0.32051928, 0.36641475, 0.70965156],
        [0.90014243, 0.53411544, 0.24729376],
        [0.67180656, 0.56172911, 0.54255988]],

       [[0.8934476 , 0.84277955, 0.30601259],
        [0.63116978, 0.68023886, 0.97042756],
        [0.89356715, 0.94242586, 0.64222548]]])

In [70]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


maxx=np.max(arr)
minn=np.min(arr)
print ("max:",maxx)
print ("min:",minn)


[[0.91909185 0.87744634 0.96165655 0.32942488 0.68643865 0.34579609
  0.45485347 0.53094214 0.19525427 0.06951846]
 [0.15901162 0.46617287 0.61941935 0.29189952 0.10718345 0.24330193
  0.99673768 0.2283235  0.22705984 0.86951035]
 [0.42016592 0.24999281 0.49009648 0.84114839 0.36925679 0.92421956
  0.99469229 0.67908565 0.40130511 0.38463964]
 [0.77664223 0.8362346  0.00804908 0.35603383 0.58146495 0.6432627
  0.8528689  0.47001505 0.46055918 0.38771978]
 [0.38761885 0.46936416 0.14160674 0.51198845 0.91123929 0.44369225
  0.01934165 0.18345392 0.33177861 0.17617143]
 [0.23704825 0.64087291 0.48507762 0.83296729 0.45256802 0.26550269
  0.32071404 0.70507318 0.26539995 0.78524858]
 [0.87905181 0.0267808  0.02730316 0.01031339 0.92751079 0.04548879
  0.53025406 0.11572938 0.30842843 0.72395218]
 [0.5574466  0.27830423 0.68308332 0.8930561  0.41729933 0.92504363
  0.29577162 0.12073912 0.45390769 0.76893908]
 [0.93816299 0.63546394 0.98587876 0.20362429 0.28969192 0.74246391
  0.12690526 

In [75]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
arr=np.random.rand(30)
print(arr)
x=np.mean(arr) 
print(x)


[0.46481713 0.561117   0.4993035  0.27774183 0.29678412 0.65078153
 0.75907282 0.08776627 0.30711411 0.98189961 0.93732725 0.5045578
 0.99291138 0.9961864  0.53060056 0.68017036 0.74364871 0.49287333
 0.39878297 0.79498449 0.95997928 0.60362413 0.0477228  0.1097562
 0.63082478 0.70525432 0.95221783 0.39021181 0.38913301 0.11736418]
0.5621509843196837


In [77]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
arr=np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

arr2 = np.ones((3, 3))
arrborder = np.pad(arr2, pad_width=1, mode='constant', constant_values=0)

print(arrborder)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [87]:
#### 17. What is the result of the following expression? (★☆☆)
x=0 * np.nan
print(x)
y=np.nan == np.nan
print(y)
z=np.inf > np.nan
print(z)

l=np.nan - np.nan
print(l)

n=np.nan in set([np.nan])
print(n)

0.3 == 3 * 0.1



nan
False
False
nan
True


False

In [95]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
arr=np.zeros((5,5))
np.fill_diagonal(arr[1:],[1,2,3,4])
arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [96]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
arr=np.zeros((8,8),dtype=int)
arr[1::2,::2]=1
arr[2::1,::2]=1
arr




array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [105]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


x = 100 // (7 * 8) 
print (x)
y=(100%(7*8))//8
print(y)
z=100%8
print(z)

1
5
4


In [108]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
arr=np.array([[1,2],[2,1]])
check=np.tile(arr,(4,4))
check

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1]])

In [113]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
arr=np.random.rand(5,5)
print(arr)
normalize=(arr-np.mean(arr)/np.std(arr))
print("after normalize:",normalize)

[[0.43291537 0.44958979 0.57167383 0.54785835 0.85452577]
 [0.69840886 0.34667343 0.17234925 0.36166467 0.98008551]
 [0.18626078 0.33396672 0.69139653 0.30101896 0.7677107 ]
 [0.71849972 0.90514647 0.99264684 0.70983706 0.65331336]
 [0.79190437 0.32096157 0.98004289 0.00855998 0.53876216]]
after normalize: [[-1.69239758 -1.67572316 -1.55363913 -1.57745461 -1.27078719]
 [-1.4269041  -1.77863952 -1.95296371 -1.76364829 -1.14522745]
 [-1.93905217 -1.79134623 -1.43391642 -1.82429399 -1.35760225]
 [-1.40681323 -1.22016648 -1.13266612 -1.4154759  -1.4719996 ]
 [-1.33340859 -1.80435139 -1.14527007 -2.11675297 -1.5865508 ]]


In [114]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
import numpy as np

# Define the custom dtype for RGBA color
rgba_dtype = np.dtype([('R', np.uint8),    # Red channel (0-255)
                       ('G', np.uint8),    # Green channel (0-255)
                       ('B', np.uint8),    # Blue channel (0-255)
                       ('A', np.uint8)])   # Alpha channel (transparency, 0-255)
9
# Create an example color using the custom dtype
color = np.array((255, 127, 64, 255), dtype=rgba_dtype)

print("RGBA Color:")
print(color)

RGBA Color:
(255, 127, 64, 255)


In [117]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
arr1=np.random.rand(5,3)
arr2=np.random.rand(3,2)
res=np.dot(arr1,arr2)
print(res)



[[1.14885022 1.57300616]
 [0.64162158 1.11672053]
 [0.77113752 1.1409988 ]
 [0.46049494 0.84300258]
 [0.99141413 1.1751746 ]]


In [121]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
arr=np.array([1,2,3,4,5])
arr[(arr>3)&(arr<8)]*=-1
arr


array([ 1,  2,  3, -4, -5])

In [124]:
#### 26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas
print(sum(range(5),-1))
print(sum(range(5),-1))


9
9


In [126]:
#### 29. How to round away from zero a float array ? (★☆☆)

arr=np.array([-1.5,2.5,3.0,4.7,1.5,-1.2])
rounded=np.round(arr,decimals=-1)
rounded



array([-0.,  0.,  0.,  0.,  0., -0.])

In [129]:
#### 30. How to find common values between two arrays? (★☆☆)
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,4,5])
x=np.intersect1d(arr1,arr2)
x



array([4, 5])

In [133]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
np.seterr(all='ignore')


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

Result: [inf inf]


In [137]:
#### 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)


False

In [145]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)



Yesterday: 2024-03-06
Today: 2024-03-07
Tomorrow: 2024-03-08


In [169]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
s=np.datetime64('2016-07-01')
e=np.datetime64('2016-08-01')
dater=np.arange(s,e,dtype='datetime64[D]')
july2016=dater[(dater>=s)&(dater<=e)]
print(' the dates corresponding to july 16  :' )
print(dater)

 the dates corresponding to july 16  :
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [180]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])
A *= -0.5           # Multiply A by -0.5 in place
A += B             # Add B to the result in A

print("Result:", A)

Result: [3.5 4.  4.5]


In [187]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
arr1=np.random.rand(3)*5
rarr=np.floor(arr1)
print(rarr)
rarr2=np.trunc(arr1)
print(rarr2)
rarr3=arr1.astype(int)
print(rarr3)
rarr4=np.int16(arr1)
print(rarr4)



[4. 0. 0.]
[4. 0. 0.]
[4 0 0]
[4 0 0]


In [193]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
matrix = np.arange(5).reshape(1, -1) + np.arange(5).reshape(-1, 1)
print (matrix)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [205]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generates() :
    for i in range (10):
        
        yield i

array = np.fromiter(generates(), dtype=int)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
vector = np.linspace(0, 1, 12)[1:-1]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [209]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
ve=np.random.rand(10)
ve.sort(axis=-1)
ve

array([0.19953075, 0.22385428, 0.2340155 , 0.28261279, 0.40240678,
       0.56821838, 0.58873061, 0.60675449, 0.62630734, 0.85650639])

In [216]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
arr=np.array([1,2,3,4,5,6])
res=sum(arr)
res

21

In [219]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([1,2,3,4,5,6])
if (arr1.all()==arr2.all()):
      print('true')
else:
    print('false')




true


In [220]:
#### 43. Make an array immutable (read-only) (★★☆)
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False
print("Array:", arr)

Array: [1 2 3 4 5]


In [224]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
arr=np.random.rand(10,2)
print(arr)
x=arr[:,0]
y=arr[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
polar_coordinates = np.column_stack((r, t))
print("after polar",polar_coordinates)

[[0.3049289  0.12231346]
 [0.24802411 0.37945102]
 [0.4443834  0.77862098]
 [0.72362641 0.77443801]
 [0.01680349 0.11771515]
 [0.49962981 0.12270687]
 [0.10810013 0.25483658]
 [0.84859297 0.95021455]
 [0.11309157 0.57982555]
 [0.55673441 0.35275393]]
after polar [[0.32854561 0.38147261]
 [0.45332001 0.99186695]
 [0.89650836 1.05217597]
 [1.05990066 0.81930334]
 [0.11890843 1.42900713]
 [0.51447733 0.24082904]
 [0.2768164  1.16960863]
 [1.27397713 0.84183203]
 [0.59075153 1.37817053]
 [0.65908159 0.56476868]]


In [236]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
ve=np.random.rand(10)
maxx=np.argmax(ve)
ve[maxx]=0
print( 'maximum value replaced by 0:')
print (ve)

maximum value replaced by 0:
[0.65134337 0.55281761 0.44245459 0.33330573 0.12807583 0.
 0.84020568 0.14220798 0.84868583 0.34534243]


In [238]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
grid_size = 5 
x_coordinates = np.linspace(0, 1, grid_size)
y_coordinates = np.linspace(0, 1, grid_size)

x_mesh, y_mesh = np.meshgrid(x_coordinates, y_coordinates)

structured_array = np.zeros((grid_size, grid_size), dtype=[('x', float), ('y', float)])
structured_array['x'] = x_mesh
structured_array['y'] = y_mesh

print("Structured Array with 'x' and 'y' coordinates:")
print(structured_array)

Structured Array with 'x' and 'y' coordinates:
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [240]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
x=np.array([1,2,3,4])
y=np.array([6,7,8,9])
c=1/(x[:,np.newaxis]-y)
c

array([[-0.2       , -0.16666667, -0.14285714, -0.125     ],
       [-0.25      , -0.2       , -0.16666667, -0.14285714],
       [-0.33333333, -0.25      , -0.2       , -0.16666667],
       [-0.5       , -0.33333333, -0.25      , -0.2       ]])

In [241]:
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
integer_types = [np.int8, np.int16, np.int32, np.int64,
                 np.uint8, np.uint16, np.uint32, np.uint64]

print("Integer types:")
for dtype in integer_types:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__:>8}: min={info.min}, max={info.max}")

Integer types:
    int8: min=-128, max=127
   int16: min=-32768, max=32767
   int32: min=-2147483648, max=2147483647
   int64: min=-9223372036854775808, max=9223372036854775807
   uint8: min=0, max=255
  uint16: min=0, max=65535
  uint32: min=0, max=4294967295
  uint64: min=0, max=18446744073709551615


In [1]:
#### 49. How to print all the values of an array? (★★☆)
array = [1, 2, 3, 4, 5]
for value in array:
    print(value)

1
2
3
4
5


In [2]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
import numpy as np

def find_closest_value(vector, scalar):
    array = np.array(vector)
    closest_value = array[np.argmin(np.abs(array - scalar))]
    return closest_value

# Example usage:
vector = [1, 3, 5, 7, 9]
scalar = 6
closest = find_closest_value(vector, scalar)
print("Closest value to", scalar, "in the vector is:", closest)


Closest value to 6 in the vector is: 5
